# This file created by conda-build 3.21.5
# meta.yaml template originally from:
# /feedstock/recipe, last modified Fri Jan  7 17:45:54 2022
# ------------------------------------------------

package:
  name: bleach
  version: 4.1.0
source:
  sha256: 0900d8b37eba61a802ee40ac0061f8c2b5dee29c1927dd1d233e075ebf5a71da
  url: https://pypi.io/packages/source/b/bleach/bleach-4.1.0.tar.gz
build:
  noarch: python
  number: '0'
  script: /opt/conda/conda-bld/bleach_1641577558959/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/bin/python
    -m pip install . -vvv
  string: pyhd3eb1b0_0
requirements:
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 4.5 1_gnu
    - bzip2 1.0.8 h7b6447c_0
    - ca-certificates 2021.10.26 h06a4308_2
    - certifi 2021.5.30 py310h06a4308_0
    - ld_impl_linux-64 2.35.1 h7274673_9
    - libffi 3.3 he6710b0_2
    - libgcc-ng 9.3.0 h5101ec6_17
    - libgomp 9.3.0 h5101ec6_17
    - libstdcxx-ng 9.3.0 hd4cf53a_17
    - libuuid 1.0.3 h7f8727e_2
    - ncurses 6.3 h7f8727e_2
    - openssl 1.1.1l h7f8727e_0
    - pip 21.2.4 py310h06a4308_0
    - python 3.10.0 h12debd9_4
    - readline 8.1 h27cfd23_0
    - setuptools 58.0.4 py310h06a4308_0
    - sqlite 3.37.0 hc218d9a_0
    - tk 8.6.11 h1ccaba5_0
    - tzdata 2021e hda174b7_0
    - wheel 0.37.0 pyhd3eb1b0_1
    - xz 5.2.5 h7b6447c_0
    - zlib 1.2.11 h7f8727e_4
  run:
    - packaging
    - python >=3.6
    - six >=1.9.0
    - webencodings
test:
  commands:
    - pip check
  imports:
    - bleach
  requires:
    - pip
about:
  description: 'Bleach is an allowed-list-based HTML sanitizing library that escapes
    or

    strips markup and attributes.

    '
  dev_url: https://github.com/mozilla/bleach
  doc_source_url: https://github.com/mozilla/bleach/blob/master/docs/index.rst
  doc_url: https://bleach.readthedocs.io/
  home: https://github.com/mozilla/bleach
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Easy, whitelist-based HTML-sanitizing tool
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - minrk
    - ocefpaf
