c_compiler: vs2017
cpu_optimization_target: nocona
cran_mirror: https://cran.r-project.org
cross_compiler_target_platform: win-32
cxx_compiler: vs2017
extend_keys:
- extend_keys
- ignore_version
- pin_run_as_build
- ignore_build_only_deps
fortran_compiler: gfortran
ignore_build_only_deps:
- python
- numpy
lua: '5'
numpy: '1.16'
perl: 5.26.2
pin_run_as_build:
  python:
    max_pin: x.x
    min_pin: x.x
  r-base:
    max_pin: x.x
    min_pin: x.x
python: '3.9'
r_base: '3.5'
target_platform: win-64
vc: '14'
