# This file created by conda-build 3.21.8
# meta.yaml template originally from:
# C:\ci\containers\00002jivuva\tmp\build\80754af9\rsync-recipes\astropy-5.0.4-python_3.9-numpy_1.16-on-winbuilder, last modified Fri Apr 22 08:14:49 2022
# ------------------------------------------------

package:
  name: astropy
  version: 5.0.4
source:
  sha256: 001184f1a9c3f526a363883ce28efb9cbf076df3d151ca3e131509a248f0dfb9
  url: https://pypi.io/packages/source/a/astropy/astropy-5.0.4.tar.gz
build:
  detect_binary_files_with_prefix: false
  entry_points:
    - fits2bitmap = astropy.visualization.scripts.fits2bitmap:main
    - fitscheck = astropy.io.fits.scripts.fitscheck:main
    - fitsdiff = astropy.io.fits.scripts.fitsdiff:main
    - fitsheader = astropy.io.fits.scripts.fitsheader:main
    - fitsinfo = astropy.io.fits.scripts.fitsinfo:main
    - samp_hub = astropy.samp.hub_script:hub_script
    - showtable = astropy.table.scripts.showtable:main
    - volint = astropy.io.votable.volint:main
    - wcslint = astropy.wcs.wcslint:main
  number: '0'
  script: C:\\ci\\astropy_1650634291321\\_h_env\\python.exe -m pip install . -vv
  string: py39h080aedc_0
requirements:
  build:
    - glib 2.69.1 h5dc1a3c_1
    - libffi 3.4.2 h604cdb4_1
    - libiconv 1.15 h1df5818_7
    - pcre 8.45 hd77b12b_0
    - pkg-config 0.29.2 h8cc25b3_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - vs2017_win-64 19.16.27032.1 hb4161e2_3
    - vswhere 2.8.4 haa95532_0
    - zlib 1.2.12 h8cc25b3_1
  host:
    - blas 1.0 mkl
    - ca-certificates 2022.3.29 haa95532_1
    - certifi 2021.10.8 py39haa95532_2
    - cython 0.29.28 py39hd77b12b_0
    - extension-helpers 0.1 pyhd3eb1b0_0
    - icc_rt 2019.0.0 h0cc432a_1
    - intel-openmp 2021.4.0 haa95532_3556
    - jinja2 3.0.3 pyhd3eb1b0_0
    - markupsafe 2.0.1 py39h2bbff1b_0
    - mkl 2021.4.0 haa95532_640
    - mkl-service 2.4.0 py39h2bbff1b_0
    - mkl_fft 1.3.1 py39h277e83a_0
    - mkl_random 1.2.2 py39hf11a4ad_0
    - numpy 1.16.6 py39ha4e8547_3
    - numpy-base 1.16.6 py39h5bb6eb2_3
    - openssl 1.1.1n h2bbff1b_0
    - packaging 21.3 pyhd3eb1b0_0
    - pip 21.2.4 py39haa95532_0
    - pyparsing 3.0.4 pyhd3eb1b0_0
    - python 3.9.12 h6244533_0
    - setuptools 61.2.0 py39haa95532_0
    - setuptools-scm 6.3.2 pyhd3eb1b0_0
    - setuptools_scm 6.3.2 hd3eb1b0_0
    - six 1.16.0 pyhd3eb1b0_1
    - sqlite 3.38.2 h2bbff1b_0
    - tomli 1.2.2 pyhd3eb1b0_0
    - tzdata 2022a hda174b7_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - wheel 0.37.1 pyhd3eb1b0_0
    - wincertstore 0.2 py39haa95532_2
  run:
    - numpy >=1.16.6,<2.0a0
    - packaging >=19.0
    - pyerfa >=2.0
    - python >=3.9,<3.10.0a0
    - pyyaml >=3.13
    - vc >=14.1,<15.0a0
    - vs2015_runtime >=14.16.27012,<15.0a0
test:
  commands:
    - pip check
    - fits2bitmap --help
    - fitscheck --help
    - fitsdiff --help
    - fitsheader --help
    - fitsinfo --help
    - samp_hub --help
    - volint --help
    - wcslint --help
    - showtable --help
  imports:
    - astropy
  requires:
    - pip
    - pytest-astropy >=0.9
    - pytest-xdist
about:
  description: 'The Astropy Project is a community effort to develop a single package
    for

    Astronomy in Python. It contains core functionality and common tools

    needed for performing astronomy and astrophysics research with Python.

    '
  dev_url: https://github.com/astropy/astropy
  doc_url: https://docs.astropy.org/en/stable/
  home: https://www.astropy.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: Community-developed Python Library for Astronomy
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - astrofrog-conda-forge
    - bsipocz
    - mwcraig
