# This file created by conda-build 3.21.8
# meta.yaml template originally from:
# C:\ci\containers\00002ogd1hr\tmp\build\80754af9\rsync-recipes\bokeh-2.4.2-python_3.9-on-winbuilder, last modified Wed May 18 12:20:09 2022
# ------------------------------------------------

package:
  name: bokeh
  version: 2.4.2
source:
  sha256: f0a4b53364ed3b7eb936c5cb1a4f4132369e394c7ae0a8ef420459410958033d
  url: https://pypi.io/packages/source/b/bokeh/bokeh-2.4.2.tar.gz
build:
  entry_points:
    - bokeh = bokeh.__main__:main
  number: '1'
  script:
    - C:\\ci\\bokeh_1652948836340\\_h_env\\python.exe -m pip install . -vv
  string: py39haa95532_1
requirements:
  host:
    - ca-certificates 2022.4.26 haa95532_0
    - certifi 2021.10.8 py39haa95532_2
    - openssl 1.1.1o h2bbff1b_0
    - pip 21.2.4 py39haa95532_0
    - python 3.9.12 h6244533_0
    - setuptools 61.2.0 py39haa95532_0
    - sqlite 3.38.3 h2bbff1b_0
    - tzdata 2022a hda174b7_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - wheel 0.37.1 pyhd3eb1b0_0
    - wincertstore 0.2 py39haa95532_2
  run:
    - jinja2 >=2.9
    - numpy >=1.11.3
    - packaging >=16.8
    - pillow >=7.1.0
    - python >=3.9,<3.10.0a0
    - pyyaml >=3.10
    - tornado >=5.1
    - typing_extensions >=3.10.0
test:
  commands:
    - pip check || 1
    - bokeh --help
  imports:
    - bokeh
    - bokeh.application
    - bokeh.application.handlers
    - bokeh.client
    - bokeh.command
    - bokeh.command.subcommands
    - bokeh.core
    - bokeh.core.property
    - bokeh.core.validation
    - bokeh.models
    - bokeh.models.widgets
    - bokeh.plotting
    - bokeh.protocol
    - bokeh.protocol.messages
    - bokeh.sampledata
    - bokeh.server
    - bokeh.server.views
    - bokeh.sphinxext
    - bokeh.themes
    - bokeh.util
  requires:
    - pip
about:
  description: 'Bokeh is an interactive visualization library for modern web browsers.

    It provides elegant, concise construction of versatile graphics,

    and affords high-performance interactivity over large or streaming

    datasets. Bokeh can help anyone who would like to quickly and easily

    make interactive plots, dashboards, and data applications.

    '
  dev_url: https://github.com/bokeh/bokeh
  doc_source_url: https://github.com/bokeh/bokeh/tree/main/sphinx/source/docs
  doc_url: https://docs.bokeh.org/en/latest/docs/user_guide.html
  home: https://bokeh.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Bokeh is an interactive visualization library for modern web browsers.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - almarklein
    - jakirkham
    - mattpap
    - ocefpaf
    - philippjfr
