# This file created by conda-build 3.21.9
# meta.yaml template originally from:
# C:\Windows\TEMP\abs_3acfc000-3a5d-484a-a556-c0e898b4a523voo0_b5v\clone\recipe, last modified Thu Jul  7 06:36:51 2022
# ------------------------------------------------

package:
  name: bkcharts
  version: '0.2'
source:
  fn: bkcharts-0.2.tar.gz
  sha256: a5eaa8e78853dcecaa46345812e4fabe9cd3b96330ebf0809f640a4a0556d72e
  url: https://pypi.io/packages/source/b/bkcharts/bkcharts-0.2.tar.gz
build:
  number: '1'
  script: python setup.py install --single-version-externally-managed --record record.txt
  string: py39haa95532_1
requirements:
  host:
    - ca-certificates 2022.4.26 haa95532_0
    - certifi 2022.6.15 py39haa95532_0
    - openssl 1.1.1p h2bbff1b_0
    - pip 21.2.4 py39haa95532_0
    - python 3.9.12 h6244533_0
    - setuptools 61.2.0 py39haa95532_0
    - sqlite 3.38.5 h2bbff1b_0
    - tzdata 2022a hda174b7_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - wheel 0.37.1 pyhd3eb1b0_0
    - wincertstore 0.2 py39haa95532_2
  run:
    - numpy >=1.7.1
    - pandas
    - python >=3.9,<3.10.0a0
    - six >=1.5.2
test:
  commands:
    - pip check
  requires:
    - pip
about:
  dev_url: https://github.com/bokeh/bkcharts
  home: https://github.com/bokeh/bkcharts
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: High level chart types built on top of Bokeh
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 3acfc000-3a5d-484a-a556-c0e898b4a523
  recipe-maintainers:
    - jakirkham
  remote_url: git@github.com:AnacondaRecipes/bkcharts-feedstock.git
  sha: 90dcd821c69018b49634dc649d438822e9ee4c82
