# This file created by conda-build 3.21.7
# meta.yaml template originally from:
# C:\ci\containers\000020s0jvs\tmp\build\80754af9\rsync-recipes\argon2-cffi-bindings-21.2.0-python_3.9-on-winbuilder, last modified Fri Feb 11 02:47:44 2022
# ------------------------------------------------

package:
  name: argon2-cffi-bindings
  version: 21.2.0
source:
  sha256: bb89ceffa6c791807d1305ceb77dbfacc5aa499891d2c55661c6459651fc39e3
  url: https://pypi.io/packages/source/a/argon2-cffi-bindings/argon2-cffi-bindings-21.2.0.tar.gz
build:
  number: '0'
  script:
    - C:\\ci\\argon2-cffi-bindings_1644551690056\\_h_env\\python.exe -m pip install
      . -vv
  string: py39h2bbff1b_0
requirements:
  build:
    - vs2017_win-64 19.16.27032.1 hb4161e2_3
    - vswhere 2.8.4 haa95532_0
  host:
    - ca-certificates 2021.10.26 haa95532_4
    - certifi 2021.10.8 py39haa95532_2
    - cffi 1.15.0 py39h2bbff1b_1
    - openssl 1.1.1m h2bbff1b_0
    - packaging 21.3 pyhd3eb1b0_0
    - pip 21.2.4 py39haa95532_0
    - pycparser 2.21 pyhd3eb1b0_0
    - pyparsing 3.0.4 pyhd3eb1b0_0
    - python 3.9.7 h6244533_1
    - setuptools 58.0.4 py39haa95532_0
    - setuptools-scm 6.3.2 pyhd3eb1b0_0
    - setuptools_scm 6.3.2 hd3eb1b0_0
    - sqlite 3.37.2 h2bbff1b_0
    - tomli 1.2.2 pyhd3eb1b0_0
    - tzdata 2021e hda174b7_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - wheel 0.37.1 pyhd3eb1b0_0
    - wincertstore 0.2 py39haa95532_2
  run:
    - cffi >=1.0.1
    - python >=3.9,<3.10.0a0
    - vc >=14.1,<15.0a0
    - vs2015_runtime >=14.16.27012,<15.0a0
test:
  commands:
    - pip check
  imports:
    - _argon2_cffi_bindings
  requires:
    - pip
about:
  description: 'argon2-cffi-bindings provides low-level CFFI bindings to the Argon2

    password hashing algorithm including a vendored version of them.

    '
  dev_url: https://github.com/hynek/argon2-cffi-bindings
  doc_url: https://github.com/hynek/argon2-cffi-bindings
  home: https://github.com/hynek/argon2-cffi-bindings
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Low-level Python CFFI Bindings for Argon2
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - stuertz
