# This file created by conda-build 3.21.7
# meta.yaml template originally from:
# /feedstock/recipe, last modified Wed Feb 16 08:30:08 2022
# ------------------------------------------------

package:
  name: argon2-cffi
  version: 21.3.0
source:
  sha256: d384164d944190a7dd7ef22c6aa3ff197da12962bd04b17f64d4e93d934dba5b
  url: https://pypi.io/packages/source/a/argon2-cffi/argon2-cffi-21.3.0.tar.gz
build:
  noarch: python
  number: '0'
  script: /opt/conda/conda-bld/argon2-cffi_1645000214183/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/bin/python
    -m pip install . -vv
  string: pyhd3eb1b0_0
requirements:
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 4.5 1_gnu
    - bzip2 1.0.8 h7b6447c_0
    - ca-certificates 2021.10.26 h06a4308_2
    - certifi 2021.5.30 py310h06a4308_0
    - flit-core 3.6.0 pyhd3eb1b0_0
    - ld_impl_linux-64 2.35.1 h7274673_9
    - libffi 3.3 he6710b0_2
    - libgcc-ng 9.3.0 h5101ec6_17
    - libgomp 9.3.0 h5101ec6_17
    - libstdcxx-ng 9.3.0 hd4cf53a_17
    - libuuid 1.0.3 h7f8727e_2
    - ncurses 6.3 h7f8727e_2
    - openssl 1.1.1m h7f8727e_0
    - pip 21.2.4 py310h06a4308_0
    - python 3.10.0 h12debd9_4
    - readline 8.1.2 h7f8727e_1
    - setuptools 58.0.4 py310h06a4308_0
    - sqlite 3.37.2 hc218d9a_0
    - tk 8.6.11 h1ccaba5_0
    - tzdata 2021e hda174b7_0
    - wheel 0.37.1 pyhd3eb1b0_0
    - xz 5.2.5 h7b6447c_0
    - zlib 1.2.11 h7f8727e_4
  run:
    - argon2-cffi-bindings
    - python >=3.6
    - typing-extensions
  run_constrained:
    - argon2_cffi ==999
test:
  commands:
    - pip check
  imports:
    - argon2
  requires:
    - pip
about:
  description: 'Argon2 won the Password Hashing Competition and argon2_cffi is the
    simplest

    way to use it in Python and PyPy

    '
  dev_url: https://github.com/hynek/argon2_cffi/
  doc_url: https://argon2-cffi.readthedocs.io/en/stable/
  home: https://argon2-cffi.readthedocs.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: The secure Argon2 password hashing algorithm.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - stuertz
