# This file created by conda-build 3.21.7
# meta.yaml template originally from:
# C:\ci\containers\00000kkc2k9\tmp\build\80754af9\rsync-recipes\anyio-3.5.0-python_3.9-on-winbuilder, last modified Thu Feb 10 02:24:46 2022
# ------------------------------------------------

package:
  name: anyio
  version: 3.5.0
source:
  - folder: dist
    sha256: a0aeffe2fb1fdf374a8e4b471444f0f3ac4fb9f5a5b542b48824475e0042a5a6
    url: https://pypi.io/packages/source/a/anyio/anyio-3.5.0.tar.gz
  - folder: src
    sha256: 55a37ea9eb2092d435af148b42a10005ee62ec7eb7d7a12d73c88e2b8aca5e38
    url: https://github.com/agronholm/anyio/archive/3.5.0.tar.gz
build:
  number: '0'
  script: cd dist && C:\\ci\\anyio_1644481921011\\_h_env\\python.exe -m pip install
    . -vv --no-deps
  string: py39haa95532_0
requirements:
  build:
    - m2-msys2-runtime 2.5.0.17080.65c939c 3
    - m2-patch 2.7.5 2
    - msys2-conda-epoch 20160418 1
  host:
    - ca-certificates 2021.10.26 haa95532_4
    - certifi 2021.10.8 py39haa95532_2
    - openssl 1.1.1m h2bbff1b_0
    - packaging 21.3 pyhd3eb1b0_0
    - pip 21.2.4 py39haa95532_0
    - pyparsing 3.0.4 pyhd3eb1b0_0
    - python 3.9.7 h6244533_1
    - setuptools 58.0.4 py39haa95532_0
    - setuptools-scm 6.3.2 pyhd3eb1b0_0
    - sqlite 3.37.2 h2bbff1b_0
    - toml 0.10.2 pyhd3eb1b0_0
    - tomli 1.2.2 pyhd3eb1b0_0
    - tzdata 2021e hda174b7_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - wheel 0.37.1 pyhd3eb1b0_0
    - wincertstore 0.2 py39haa95532_2
  run:
    - idna >=2.8
    - python >=3.9,<3.10.0a0
    - sniffio >=1.1
  run_constrained:
    - trio >=0.16
test:
  commands:
    - pip check
  downstreams: null
  imports:
    - anyio
  requires:
    - coverage >=4.5
    - hypothesis >=4.0
    - mock >=4
    - pip
    - pytest >=6.0
    - pytest-cov
    - pytest-mock >=3.6.1
    - ruamel_yaml
    - toml
    - trio
    - trustme
  source_files:
    - src/tests
about:
  dev_url: https://github.com/agronholm/anyio
  doc_source_url: https://github.com/agronholm/anyio/tree/3.5.0/docs
  doc_url: https://anyio.readthedocs.io
  home: https://github.com/agronholm/anyio
  license: MIT
  license_family: MIT
  license_file: dist/LICENSE
  summary: High level compatibility layer for multiple asynchronous event loop implementations
    on Python
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - CJ-Wright
    - bollwyvl
