# This file created by conda-build 3.21.6
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/async-timeout-4.0.1-on-linux_64, last modified Thu Nov 25 14:37:11 2021
# ------------------------------------------------

package:
  name: async-timeout
  version: 4.0.1
source:
  fn: async-timeout-4.0.1.tar.gz
  sha256: b930cb161a39042f9222f6efb7301399c87eeab394727ec5437924a36d6eef51
  url: https://pypi.io/packages/source/a/async-timeout/async-timeout-4.0.1.tar.gz
build:
  noarch: python
  number: '0'
  script: /tmp/build/80754af9/async-timeout_1637851218186/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/bin/python
    -m pip install . -vv
  string: pyhd3eb1b0_0
requirements:
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 4.5 1_gnu
    - ca-certificates 2021.10.26 h06a4308_2
    - certifi 2021.10.8 py39h06a4308_0
    - ld_impl_linux-64 2.35.1 h7274673_9
    - libffi 3.3 he6710b0_2
    - libgcc-ng 9.3.0 h5101ec6_17
    - libgomp 9.3.0 h5101ec6_17
    - libstdcxx-ng 9.3.0 hd4cf53a_17
    - ncurses 6.3 h7f8727e_2
    - openssl 1.1.1l h7f8727e_0
    - pip 21.2.4 py39h06a4308_0
    - python 3.9.7 h12debd9_1
    - readline 8.1 h27cfd23_0
    - setuptools 58.0.4 py39h06a4308_0
    - sqlite 3.36.0 hc218d9a_0
    - tk 8.6.11 h1ccaba5_0
    - tzdata 2021e hda174b7_0
    - wheel 0.37.0 pyhd3eb1b0_1
    - xz 5.2.5 h7b6447c_0
    - zlib 1.2.11 h7b6447c_3
  run:
    - python >=3.6
    - typing-extensions >=3.6.5
test:
  commands:
    - pip check
  imports:
    - async_timeout
  requires:
    - pip
    - python <3.10
about:
  dev_url: http://github.com/aio-libs/async_timeout
  doc_url: https://github.com/aio-libs/async-timeout/blob/master/README.rst
  home: http://github.com/aio-libs/async_timeout
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Timeout context manager for asyncio programs
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - sodre
