# This file created by conda-build 3.20.2
# meta.yaml template originally from:
# /tmp/build/80754af9/combined_recipe, last modified Wed Sep 16 23:20:08 2020
# ------------------------------------------------

package:
    name: automat
    version: 20.2.0
source:
    patches:
        - 0001-m2r-is-not-a-strict-build-dependency.patch
    sha256: 7979803c74610e11ef0c0d68a2942b152df52da55336e0c9d58daf1831cbdf33
    url: https://pypi.io/packages/source/A/Automat/Automat-20.2.0.tar.gz
build:
    entry_points:
        - automat-visualize = automat._visualize:tool
    noarch: python
    number: '0'
    script: /tmp/build/80754af9/automat_1600298431173/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/bin/python
        -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
    string: py_0
requirements:
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2020.7.22 0
        - certifi 2020.6.20 py36_0
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libedit 3.1.20191231 h14c3975_1
        - libffi 3.3 he6710b0_2
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.2 he6710b0_1
        - openssl 1.1.1g h7b6447c_0
        - pip 20.2.2 py36_0
        - python 3.6.12 hcff3b4d_2
        - readline 8.0 h7b6447c_0
        - setuptools 49.6.0 py36_0
        - setuptools-scm 4.1.2 py_0
        - setuptools_scm 4.1.2 0
        - sqlite 3.33.0 h62c20be_0
        - tk 8.6.10 hbc83047_0
        - wheel 0.35.1 py_0
        - xz 5.2.5 h7b6447c_0
        - zlib 1.2.11 h7b6447c_3
    run:
        - attrs >=16.1.0
        - python
        - six
test:
    commands:
        - automat-visualize -h
    imports:
        - automat
    requires:
        - python-graphviz >0.5.1
        - twisted >=16.1.1
about:
    description: 'Automat is a library for concise, idiomatic Python expression of

        finite-state automata (particularly deterministic finite-state

        transducers).

        '
    dev_url: https://github.com/glyph/automat/
    doc_url: https://github.com/glyph/automat/
    home: https://github.com/glyph/Automat
    license: MIT
    license_family: MIT
    license_file: LICENSE
    summary: self-service finite-state machines for the programmer on the go
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - CJ-Wright
        - ocefpaf
