# This file created by conda-build 3.21.6
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/aiosignal-1.2.0-on-linux_64, last modified Wed Nov 24 15:49:00 2021
# ------------------------------------------------

package:
  name: aiosignal
  version: 1.2.0
source:
  sha256: 78ed67db6c7b7ced4f98e495e572106d5c432a93e1ddd1bf475e1dc05f5b7df2
  url: https://pypi.io/packages/source/a/aiosignal/aiosignal-1.2.0.tar.gz
build:
  noarch: python
  number: '0'
  script: /tmp/build/80754af9/aiosignal_1637843061372/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin/python
    -m pip install . -vv
  string: pyhd3eb1b0_0
requirements:
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 4.5 1_gnu
    - ca-certificates 2021.10.26 h06a4308_2
    - certifi 2021.10.8 py39h06a4308_0
    - ld_impl_linux-64 2.35.1 h7274673_9
    - libffi 3.3 he6710b0_2
    - libgcc-ng 9.3.0 h5101ec6_17
    - libgomp 9.3.0 h5101ec6_17
    - libstdcxx-ng 9.3.0 hd4cf53a_17
    - ncurses 6.3 h7f8727e_2
    - openssl 1.1.1l h7f8727e_0
    - pip 21.2.4 py39h06a4308_0
    - python 3.9.7 h12debd9_1
    - readline 8.1 h27cfd23_0
    - setuptools 58.0.4 py39h06a4308_0
    - sqlite 3.36.0 hc218d9a_0
    - tk 8.6.11 h1ccaba5_0
    - tzdata 2021e hda174b7_0
    - wheel 0.37.0 pyhd3eb1b0_1
    - xz 5.2.5 h7b6447c_0
    - zlib 1.2.11 h7b6447c_3
  run:
    - frozenlist >=1.1.0
    - python >=3.6
test:
  commands:
    - pip check
  imports:
    - aiosignal
  requires:
    - pip
    - python <3.10
about:
  dev_url: https://github.com/aio-libs/aiosignal
  doc_url: https://aiosignal.readthedocs.io/en/stable/
  home: https://github.com/aio-libs/aiosignal
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'aiosignal: a list of registered asynchronous callbacks'
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - ocefpaf
