# This file created by conda-build 3.21.7
# meta.yaml template originally from:
# C:\ci\containers\00001pfppu7\tmp\build\80754af9\rsync-recipes\aiohttp-3.8.1-python_3.9-on-winbuilder, last modified Wed Mar  9 00:07:04 2022
# ------------------------------------------------

package:
  name: aiohttp
  version: 3.8.1
source:
  sha256: fc5471e1a54de15ef71c1bc6ebe80d4dc681ea600e68bfd1cbce40427f0b7578
  url: https://pypi.io/packages/source/a/aiohttp/aiohttp-3.8.1.tar.gz
build:
  number: '1'
  script: C:\\ci\\aiohttp_1646806572557\\_h_env\\python.exe -m pip install . -vv
  string: py39h2bbff1b_1
requirements:
  build:
    - vs2017_win-64 19.16.27032.1 hb4161e2_3
    - vswhere 2.8.4 haa95532_0
  host:
    - ca-certificates 2022.2.1 haa95532_0
    - certifi 2021.10.8 py39haa95532_2
    - cython 0.29.25 py39h604cdb4_0
    - openssl 1.1.1m h2bbff1b_0
    - pip 21.2.4 py39haa95532_0
    - python 3.9.7 h6244533_1
    - setuptools 58.0.4 py39haa95532_0
    - sqlite 3.37.2 h2bbff1b_0
    - tzdata 2021e hda174b7_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - wheel 0.37.1 pyhd3eb1b0_0
    - wincertstore 0.2 py39haa95532_2
  run:
    - aiosignal >=1.1.2
    - async-timeout >=4.0.0a3,<5.0
    - attrs >=17.3.0
    - charset-normalizer >=2.0,<3.0
    - frozenlist >=1.1.1
    - multidict >=4.5,<7.0
    - python >=3.9,<3.10.0a0
    - vc >=14.1,<15.0a0
    - vs2015_runtime >=14.16.27012,<15.0a0
    - yarl >=1.0,<2.0
test:
  commands:
    - pip check
  imports:
    - aiohttp
  requires:
    - pip
about:
  dev_url: https://github.com/aio-libs/aiohttp
  doc_source_url: https://github.com/aio-libs/aiohttp/tree/master/docs
  doc_url: https://aiohttp.readthedocs.io/
  home: https://github.com/aio-libs/aiohttp
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: Async http client/server framework (asyncio)
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - ocefpaf
    - sodre
    - xhochy
