# This file created by conda-build 3.21.8
# meta.yaml template originally from:
# C:\ci\containers\00002cd3kof\tmp\build\80754af9\rsync-recipes\bitarray-2.5.0-python_3.9-on-winbuilder, last modified Tue May 10 08:45:11 2022
# ------------------------------------------------

package:
  name: bitarray
  version: 2.5.0
source:
  sha256: 5abed04adcd2031f6e714993d95223bf9ae85354c640c270b2ed6f46b83573ba
  url: https://pypi.io/packages/source/b/bitarray/bitarray-2.5.0.tar.gz
build:
  number: '0'
  script: C:\\ci\\bitarray_1652190698176\\_h_env\\python.exe -m pip install . --no-deps
    -vv
  string: py39h2bbff1b_0
requirements:
  build:
    - vs2017_win-64 19.16.27032.1 hb4161e2_3
    - vswhere 2.8.4 haa95532_0
  host:
    - ca-certificates 2022.4.26 haa95532_0
    - certifi 2021.10.8 py39haa95532_2
    - openssl 1.1.1o h2bbff1b_0
    - pip 21.2.4 py39haa95532_0
    - python 3.9.12 h6244533_0
    - setuptools 61.2.0 py39haa95532_0
    - sqlite 3.38.3 h2bbff1b_0
    - tzdata 2022a hda174b7_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - wheel 0.37.1 pyhd3eb1b0_0
    - wincertstore 0.2 py39haa95532_2
  run:
    - python >=3.9,<3.10.0a0
    - vc >=14.1,<15.0a0
    - vs2015_runtime >=14.16.27012,<15.0a0
test:
  commands:
    - pip check
  imports:
    - bitarray
  requires:
    - pip
about:
  description: 'Bitarray provides an object type which efficiently represents an array
    of

    booleans. Bitarrays are sequence types that behave very similarly

    to usual lists. All functionality is implemented in C.

    '
  dev_url: https://github.com/ilanschnell/bitarray
  doc_source_url: https://github.com/ilanschnell/bitarray/blob/master/README.rst
  doc_url: https://pypi.python.org/pypi/bitarray/2.5.0
  home: https://github.com/ilanschnell/bitarray
  license: PSF-2.0
  license_family: PSF
  license_file: LICENSE
  summary: efficient arrays of booleans -- C extension
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - nehaljwani
