# This file created by conda-build 3.21.8
# meta.yaml template originally from:
# C:\ci\containers\00003nr0o52\tmp\build\80754af9\rsync-recipes\beautifulsoup4-4.11.1-python_3.9-on-winbuilder, last modified Mon Apr 18 09:38:50 2022
# ------------------------------------------------

package:
  name: beautifulsoup4
  version: 4.11.1
source:
  sha256: ad9aa55b65ef2808eb405f46cf74df7fcb7044d5cbc26487f96eb2ef2e436693
  url: https://pypi.io/packages/source/b/beautifulsoup4/beautifulsoup4-4.11.1.tar.gz
build:
  number: '0'
  string: py39haa95532_0
requirements:
  host:
    - ca-certificates 2022.3.29 haa95532_0
    - certifi 2021.10.8 py39haa95532_2
    - openssl 1.1.1n h2bbff1b_0
    - pip 21.2.4 py39haa95532_0
    - python 3.9.12 h6244533_0
    - setuptools 61.2.0 py39haa95532_0
    - sqlite 3.38.2 h2bbff1b_0
    - tzdata 2022a hda174b7_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - wheel 0.37.1 pyhd3eb1b0_0
    - wincertstore 0.2 py39haa95532_2
  run:
    - python >=3.9,<3.10.0a0
    - soupsieve >=1.2
test:
  commands:
    - pip check
  imports:
    - bs4
    - bs4.builder
  requires:
    - pip
about:
  description: 'Beautiful Soup is a library for pulling data out of HTML and XML files.

    It provides ways of navigating, searching, and modifying parse trees.

    '
  dev_url: https://code.launchpad.net/beautifulsoup
  doc_source_url: https://github.com/newvem/beautifulsoup4/blob/master/doc/source/index.rst
  doc_url: https://beautiful-soup-4.readthedocs.io/en/latest/
  home: https://www.crummy.com/software/BeautifulSoup/
  license: MIT
  license_family: MIT
  license_file: COPYING.txt
  summary: Python library designed for screen-scraping
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - jschueller
    - nehaljwani
